config:
  target: "http://localhost:8080"
  phases:
    - duration: 30
      arrivalRate: 10
      name: Warm up
    - duration: 20
      arrivalRate: 20
      rampTo: 200
      name: Ramp up load
    - duration: 20
      arrivalRate: 200
      name: Sustained load
    - duration: 30
      arrivalRate: 200
      rampTo: 20
      name: End of load

scenarios:
  - name: "get posts"
    flow:
      - get:
          url: "/post"


