spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/newnewsfeed
    username: root
    password: newjidong

jwt:
  secret:
    accessSecretKey: "FlRpX30MqDbiAkmlfArbrmVkDD4RqISskGZmBFax5oGVxzXXWUzTR5JyskiHMIV9M10icegkpi46AdvrcX1E6CmTUBc6ds3"
    refreshSecretKey: "7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLgbTPiDc6IFwetg"
    accessTokenExpiredTime:  86400000
    refreshTokenExpiredTime: 86400000